Calculating electric potential due to a point charge using lambda functions and maps.
ubsuny/CP1-24-HW3 pull request #40
Opened 2024-10-14 15:58 UTC by Tolani4

This Pull Request implements a Python function to calculate the electric potential V at various distances due to a point charge. The calculation is based on Coulomb's Law and uses functional programming concepts, lambda functions, list comprehension, and map() function for implementation.

2024-10-14 16:12 UTC, Tolani4 commented
After submitting my pull requests I'm still receiving errors from github specifically pylint. Am I just supposed to apply the changes it recommends such as " C0301: Line too long (108/100) (line-too-long)"

2024-10-14 16:13 UTC, laserlab commented
> After submitting my pull requests I'm still receiving errors from github specifically pylint. Am I just supposed to apply the changes it recommends such as " C0301: Line too long (108/100) (line-too-long)"

yes, since the reviewer will point it out and we want to write compliant code

2024-10-14 16:15 UTC, laserlab commented
Though your low score (1.3/10) most likely stems from more serious issues like: 
> Electric_potential_due_to_point_charge.py/Electric_potential.py:30:21: C3001: Lambda expression assigned to a variable. Define a function using the "def" keyword instead. (unnecessary-lambda-assignment)

which I discussed in class as we talked about lambda functions

2024-10-14 16:50 UTC, Tolani4 commented
Okay thank you. For the "missing module docstring" error. Do I just need to create a separate file called docstring and just explain my code and the physics behind it? and for the error "C0115: Missing class docstring (missing-class-docstring)",  Do I just create a class called docstring in that file? Just trying to understand what the errors mean.

2024-10-14 17:55 UTC, laserlab commented
As we discussed in class docstring explanation can be found in the lecture slides in hands on examples and here:

https://peps.python.org/pep-0257/

2024-10-15 14:02 UTC, laserlab commented
@ojha-aditya Please review asap

2024-10-15 15:08 UTC, ojha-aditya commented
Can I as reviewer resolve this notification about the branch being out-of-date or we simply mention it in the review as a todo?

2024-10-15 16:18 UTC, laserlab commented
> Also, do we need to have a main function in the module?

no, since it’s a module

2024-10-15 16:18 UTC, laserlab commented
> Can I as reviewer resolve this notification about the branch being out-of-date or we simply mention it in the review as a todo?

you an mention it

2024-10-16 13:13 UTC, laserlab requested changes
- no .py in folder name
- data type in docstring
- tons of linting errors

2024-10-16 13:13 UTC, laserlab commented on Electric_potential_due_to_point_charge.py/Electric_potential.py
> +    charge (float): The charge in Coulombs.
if you do not require nor check for float do not use it in docstring

2024-10-16 13:31 UTC, ojha-aditya commented
We should not mention the things you have already pointed in our review @laserlab should we?

2024-10-16 13:47 UTC, laserlab commented
> We should not mention the things you have already pointed in our review @laserlab should we?

Please mention all you noticed, independent from what I comment.

2024-10-16 14:21 UTC, ojha-aditya requested changes
Along with the ones already pointed out, here is a good explanation for the unnecessary-lambda-assignment pylint message:

https://pylint.pycqa.org/en/latest/user_guide/messages/convention/unnecessary-lambda-assignment.html
https://www.geeksforgeeks.org/overuse-of-lambda-expressions-in-python/

2024-10-16 18:37 UTC, ojha-aditya requested changes
The binary file needs to be removed as well.

2024-10-17 12:54 UTC, laserlab commented
no fixes, not merging

2024-10-17 12:54 UTC, closed without merging