Documented theory of Classical Electrodynamics example - Electric Field and implemented the code
ubsuny/CP1-24-HW3 pull request #44
Opened 2024-10-14 16:32 UTC by Cosmos491

The documentation includes the theory aspect related to Electric Field ( example of Classical Electrodynamics) and how along with the Maxwell's equations they describe a great deal pf physics. The python file includes a code which calculates the Electric field due to a single charge and then the net Electric Field due to multiple charges using the superposition principle.

2024-10-15 14:02 UTC, laserlab commented
@abruns123 Please review asap

2024-10-15 22:58 UTC, abruns123 requested changes
Code runs fine, albeit it only gets a 6.5 score for linting; however, there's a severe issue with the physics of your simulation. The electric field is a vector, but your code is treating it purely as a magnitude. So, for example if we had two equal charges spaced equally apart from the origin on the same axis, I would expect that the electric field components at the origin would be of equal magnitude and opposite direction such that they cancel out. Your code instead just adds their magnitudes together. With some modification, you could easily get this code to determine the electric potential at a certain point due to point charges, but to get electric field accurately, you need to account for the vectors.

2024-10-16 06:30 UTC, abruns123 requested changes
Your Electric_FIeld_due_to_single_charge module doesn't run due to an indent error on line 52

2024-10-16 08:53 UTC, Cosmos491 commented
Yes, I am working on that. Thank you for letting me know. I believe I will be able to implement the changes before the class tomorrow.

2024-10-16 13:33 UTC, laserlab requested changes
- check linting issues
- main loop

2024-10-16 13:33 UTC, laserlab commented on electric_field_due_to_single_charge.py
> +# Example
Examples should go into the docstring

2024-10-16 13:33 UTC, laserlab commented on electric_field_due_to_single_charge.py
> +separation_vector = lambda p, o: (p[0] - o[0], p[1] - o[1])  # Separation vector between two points
Agreeing here with the linter:
electric_field_due_to_single_charge.py:12:20: C3001: Lambda expression assigned to a variable. Define a function using the "def" keyword instead. (unnecessary-lambda-assignment)
just use a function here

2024-10-16 13:33 UTC, laserlab commented on electric_field_due_to_single_charge.py
> +magnitude = lambda v: np.sqrt(v[0]**2 + v[1]**2)  # Magnitude of a 2D vector
see above

2024-10-16 20:52 UTC, Cosmos491 commented
@laserlab and @abruns123 , I have made the changes as requested.

2024-10-17 12:58 UTC, laserlab approved these changes

2024-10-17 12:58 UTC, merged