Electric Field of a Sphere
ubsuny/CP1-24-HW3 pull request #45
Opened 2024-10-14 17:45 UTC by abruns123

The electricSphere module uses the getField function to produce the vector which defines the electric field of a spherical shell that may be defined by the user in terms of its center relative to the origin, its charge density, and radius. The user also determines the point at which the electric field is measured. 

This is all tested by electricSphereTester.

The theory markdown file goes over how to determine the electric field of a sphere with constant volume charge density.

2024-10-15 14:03 UTC, laserlab commented
@Cosmos491 please review asap

2024-10-15 19:39 UTC, Cosmos491 commented
@laserlab I am on it, professor.

2024-10-15 20:25 UTC, Cosmos491 commented
I will start from the beginning:

1. The first code calculates the electric field produced by a charged sphere. If the point lies inside the sphere, the field magnitude is calculated using a smaller effective radius.  The elecField function provides the direction and magnitude of the electric field at point p relative to the sphere center o.

2.  The second code is the unit test code for the electricSphere module.

3. The explanation concludes with the fact that: Inside the sphere, the electric field has a linear relationship with r. Outside, the electric field has a decreasing parabolic relationship with r. It also mentions that the electric field is a vector quantity and that the derived equations describe the magnitude of the electric field in the radial direction from the center.


Below I will review them in the same manner:

1. There is a potential issue with dividing by zero in getUVec(), when the magnitude is zero. So, I suggest adding error handling for potential division by zero in getUVec. Simplify the implementation of zeroCondition for better readability.

2. Simplify and improve the readability of the test_behavior function by breaking down the logic into smaller parts. Replace floating-point equality checks with assert_allclose to prevent errors due to rounding. 

3. The phrase "sphereical shell" should be corrected to "spherical shell".  Consider breaking down the explanation into smaller sections for clarity. But, overall the theory looks fine.

2024-10-16 02:18 UTC, abruns123 commented
At this time, I have made adjustments according to your specifications.

2024-10-16 13:04 UTC, laserlab requested changes
- lambda function use
- main loop

2024-10-16 15:39 UTC, abruns123 commented on electricSphere.py
> +v=lambda r:4/3*np.pi*r**3
Okay, I've adjusted the implementation such that I have get_volume, get_area, etc functions and each return a lambda function defining volume, area etc. This got rid of the linting error involving the unnecessary lambda assignment.

2024-10-16 15:40 UTC, abruns123 commented on electricSphere.py
> +if __name__=="__main__":
The main loop allows the user to test the module with some control over origin of sphere, charge density, radius of sphere, and the point where the field is measured. I added a docstring to explain that more thoroughly.

2024-10-17 13:00 UTC, laserlab commented on electricSphere.py
> +if __name__=="__main__":
testing should be done in the unit test

2024-10-17 13:00 UTC, laserlab commented
main loop is not for testing, merging anyway

2024-10-17 13:00 UTC, merged