Electrostatic Potential
ubsuny/CP1-24-HW3 pull request #48
Opened 2024-10-14 19:09 UTC by iglesias-cardinale

Added a module to find electrostatic potential from a set charge distribution. This could be expanded to include continuous charge distributions. Module includes lambda functions and iterators (np.enumerate). 

Added brief documentation on the theory of electrostatic potential. This should be added to.

Added unit test module to test
- Vector potential is zero when charge is zero
- Potential due to single charge at origin matched Coulomb's law
- Potential function returns infinity if charge and observation point overlap.

2024-10-14 20:04 UTC, HeshamElsaman commented on __pycache__/electrostatics.cpython-312.pyc
Please, remove this file.

2024-10-14 20:23 UTC, HeshamElsaman requested changes
- I'm actually not sure about linting, even for myself, but the code is well-functioning.
- Two of the functional programming concepts were utilized.
- Modules are well-separated.
However,
- The files need to be moved into a different folder not to possibly conflict with similarly named files from other people and for a better modularity.
- A binary file needs to be removed. It probably happened because the PR was created before updating the branch to include the .gitignore file.

2024-10-15 14:27 UTC, laserlab commented
> * I'm actually not sure about linting, even for myself, but the code is well-functioning.

The main linting complain that you could have picked up too for the review are the missing docstrings.

2024-10-16 13:07 UTC, laserlab requested changes
- linting
- lambda function use
- no ED function as argument in another function

2024-10-16 13:07 UTC, laserlab commented on electrostatics.py
> +r_xp = lambda x, p: np.linalg.norm(x - p, axis=1)
Agree with the linter here. Not useful use of lambda function. Also it doesn’t fulfill the homework requirement of using your ED function as an argument in another function

2024-10-17 13:04 UTC, closed without merging